version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
              - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test

  deploy-to-staging:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Deploy scripts
          command: echo 'TO DO - deploy job'
    
workflows:
  build-tests-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: 
                - master
      - deploy-to-staging:
          requires:
            - hold
          filters:
            tags:
                only: /.*/